import { cpSync, mkdirSync, readdirSync, writeFileSync } from 'fs';
import { join, relative } from 'path';
import { execSync } from 'child_process';

console.log('Building Next.js static export...');
execSync('npm run build', { stdio: 'inherit' });

const outputDir = '.vercel/output';
const staticDir = join(outputDir, 'static');
mkdirSync(staticDir, { recursive: true });

console.log('Copying static files...');
cpSync('out', staticDir, { recursive: true });

const overrides = {};
function findIndexFiles(dir) {
  const entries = readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      findIndexFiles(fullPath);
    } else if (entry.name === 'index.html') {
      const relativePath = relative(staticDir, fullPath);
      const parentDir = relative(staticDir, dir);
      if (parentDir && parentDir !== '.') {
        overrides[relativePath] = { path: parentDir };
      }
    }
  }
}

findIndexFiles(staticDir);

const config = { version: 3, overrides };
writeFileSync(join(outputDir, 'config.json'), JSON.stringify(config, null, 2));
console.log(`✅ Build complete! Generated overrides for ${Object.keys(overrides).length} pages`);
console.log('Run: vercel deploy --prebuilt');

// Fix builds.json
writeFileSync(join(outputDir, 'builds.json'), JSON.stringify({
  "//": "Generated by build-for-vercel.mjs",
  "target": "production",
  "builds": []
}));
