export type SpellingWord = {
  word: string
  misspellings: string[]
  dialects: { us: string; uk: string; au: string; nz: string } | null
  tip: string
  example: string
  difficulty: "easy" | "medium" | "hard"
  monthlySearches: string
}

export const SPELLING_WORDS: SpellingWord[] = [
  {
    word: "accommodate",
    misspellings: ["accomodate", "acommodate", "acomodate", "accommadate"],
    dialects: null,
    tip: "Two c's and two m's. Think: it's large enough to accommodate two of each.",
    example: "The hotel can accommodate up to 300 guests.",
    difficulty: "hard",
    monthlySearches: "100,000+",
  },
  {
    word: "achieve",
    misspellings: ["acheive", "acheve", "acheeve"],
    dialects: null,
    tip: "I before E, except after C. Achieve follows the rule.",
    example: "She worked hard to achieve her goals.",
    difficulty: "easy",
    monthlySearches: "30,000+",
  },
  {
    word: "acquire",
    misspellings: ["aquire", "adquire", "accquire", "aqcuire"],
    dialects: null,
    tip: "AC then QUIRE. Think: I need to ACquire new skills.",
    example: "The company plans to acquire a smaller firm.",
    difficulty: "medium",
    monthlySearches: "25,000+",
  },
  {
    word: "alphabet",
    misspellings: ["alphubet", "alfabet", "alphbet", "alphabit"],
    dialects: null,
    tip: "Alpha + bet. Two Greek letters combined.",
    example: "Children learn the alphabet in kindergarten.",
    difficulty: "easy",
    monthlySearches: "15,000+",
  },
  {
    word: "apparently",
    misspellings: ["apparantly", "aparently", "apparentley", "aparantly"],
    dialects: null,
    tip: "Parent is hiding inside: apPARENTly.",
    example: "Apparently, the meeting has been moved to Friday.",
    difficulty: "medium",
    monthlySearches: "40,000+",
  },
  {
    word: "beautiful",
    misspellings: ["beautifull", "beutiful", "beautful", "beatiful"],
    dialects: null,
    tip: "Big Elephants Are Ugly. The first letters spell BEAU.",
    example: "The sunset was absolutely beautiful.",
    difficulty: "easy",
    monthlySearches: "50,000+",
  },
  {
    word: "believe",
    misspellings: ["beleive", "belive", "beleave", "beleve"],
    dialects: null,
    tip: "Never beLIEve a LIE.",
    example: "I believe we can finish on time.",
    difficulty: "easy",
    monthlySearches: "20,000+",
  },
  {
    word: "bureaucracy",
    misspellings: ["beaurocracy", "burocracy", "beurocracy", "bureacracy"],
    dialects: null,
    tip: "BUREAU + CRACY. A bureau that rules.",
    example: "The bureaucracy made the process slow.",
    difficulty: "hard",
    monthlySearches: "25,000+",
  },
  {
    word: "calendar",
    misspellings: ["calender", "calander", "calandar", "callendar"],
    dialects: null,
    tip: "Ends in DAR, not DER. Think: Mark the DAR on the calendar.",
    example: "Please check the calendar for available dates.",
    difficulty: "easy",
    monthlySearches: "257,000",
  },
  {
    word: "Caribbean",
    misspellings: ["Carribean", "Caribean", "Caribbian", "Carribbean"],
    dialects: null,
    tip: "One R, two B's. The opposite of what you'd expect.",
    example: "They sailed across the Caribbean Sea.",
    difficulty: "hard",
    monthlySearches: "30,000+",
  },
  {
    word: "cemetery",
    misspellings: ["cemetary", "cematery", "cemetry", "cemetary"],
    dialects: null,
    tip: "Three E's, no A's. Think: E-E-E, screaming in a cemetery.",
    example: "The old cemetery dates back to the 1800s.",
    difficulty: "medium",
    monthlySearches: "20,000+",
  },
  {
    word: "colleague",
    misspellings: ["collegue", "colague", "coleague", "colleage"],
    dialects: null,
    tip: "Ends in LEAGUE, like a team of colleagues.",
    example: "My colleague helped me with the project.",
    difficulty: "medium",
    monthlySearches: "25,000+",
  },
  {
    word: "conscience",
    misspellings: ["concience", "consience", "concsience", "conshence"],
    dialects: null,
    tip: "CON + SCIENCE. Your inner science of right and wrong.",
    example: "His conscience told him to return the wallet.",
    difficulty: "hard",
    monthlySearches: "60,000+",
  },
  {
    word: "conscientious",
    misspellings: ["concientious", "consciencious", "conscienscious"],
    dialects: null,
    tip: "CONSCIENCE + TIOUS. Being guided by your conscience.",
    example: "She is a conscientious worker who checks every detail.",
    difficulty: "hard",
    monthlySearches: "25,000+",
  },
  {
    word: "congratulations",
    misspellings: ["congradulations", "congragulations", "congraulations"],
    dialects: null,
    tip: "No D. It comes from GRATULATE, not GRADUATE.",
    example: "Congratulations on your promotion!",
    difficulty: "medium",
    monthlySearches: "40,000+",
  },
  {
    word: "definitely",
    misspellings: ["definately", "definatly", "defiantly", "definetly", "definatley"],
    dialects: null,
    tip: "FINITE is in the middle: deFINITEly. No A anywhere.",
    example: "I will definitely be there by noon.",
    difficulty: "medium",
    monthlySearches: "150,000+",
  },
  {
    word: "diarrhea",
    misspellings: ["diarhea", "diarrhoea", "diarreah", "diarea"],
    dialects: { us: "diarrhea", uk: "diarrhoea", au: "diarrhoea", nz: "diarrhoea" },
    tip: "Two R's, then H. Dash In A Rush, Run Hard, Else Accident.",
    example: "The patient was treated for diarrhea.",
    difficulty: "hard",
    monthlySearches: "35,000+",
  },
  {
    word: "dilemma",
    misspellings: ["dilema", "dilemna", "dillema", "dillemma"],
    dialects: null,
    tip: "Two M's, not N. Think: Emma has a dilemma.",
    example: "He faced a dilemma between two job offers.",
    difficulty: "medium",
    monthlySearches: "15,000+",
  },
  {
    word: "disappoint",
    misspellings: ["dissapoint", "disapoint", "disappoint", "dissappoint"],
    dialects: null,
    tip: "One S, two P's. DIS + APPOINT.",
    example: "I hope the results don't disappoint you.",
    difficulty: "medium",
    monthlySearches: "20,000+",
  },
  {
    word: "embarrass",
    misspellings: ["embarass", "embarras", "embaress", "embaras"],
    dialects: null,
    tip: "Two R's and two S's. It's Really Really Stressful and Shameful.",
    example: "Please don't embarrass me in public.",
    difficulty: "medium",
    monthlySearches: "60,000+",
  },
  {
    word: "environment",
    misspellings: ["enviroment", "envirnoment", "enviornment", "enviorment"],
    dialects: null,
    tip: "IRON is hiding in the middle: envIRONment.",
    example: "We must protect the environment for future generations.",
    difficulty: "medium",
    monthlySearches: "30,000+",
  },
  {
    word: "exaggerate",
    misspellings: ["exagerate", "exadgerate", "exaggerrate", "exaggurate"],
    dialects: null,
    tip: "Two G's. You're exaGGerating with extra G's.",
    example: "Don't exaggerate the problem.",
    difficulty: "medium",
    monthlySearches: "20,000+",
  },
  {
    word: "existence",
    misspellings: ["existance", "existense", "existince"],
    dialects: null,
    tip: "Ends in ENCE, not ANCE. Think: EXIST + ENCE.",
    example: "No one questioned the existence of the document.",
    difficulty: "medium",
    monthlySearches: "15,000+",
  },
  {
    word: "foreign",
    misspellings: ["foriegn", "forein", "foregin", "foren"],
    dialects: null,
    tip: "E before I. It breaks the I before E rule. FOR + EIGN.",
    example: "She speaks three foreign languages.",
    difficulty: "medium",
    monthlySearches: "20,000+",
  },
  {
    word: "gauge",
    misspellings: ["guage", "gage", "gaige", "gauje"],
    dialects: null,
    tip: "G-A-U, not G-U-A. Think: A U-turn after the A.",
    example: "Check the fuel gauge before driving.",
    difficulty: "hard",
    monthlySearches: "30,000+",
  },
  {
    word: "government",
    misspellings: ["goverment", "govenment", "governmant", "govermnent"],
    dialects: null,
    tip: "GOVERN + MENT. Don't drop the N.",
    example: "The government announced new policies.",
    difficulty: "easy",
    monthlySearches: "25,000+",
  },
  {
    word: "guarantee",
    misspellings: ["gaurantee", "guarentee", "garantee", "guaruntee"],
    dialects: null,
    tip: "GUA at the start, not GAU. Then RANTEE.",
    example: "We guarantee delivery within 24 hours.",
    difficulty: "hard",
    monthlySearches: "60,000+",
  },
  {
    word: "harass",
    misspellings: ["harrass", "harras", "haras", "herrass"],
    dialects: null,
    tip: "One R, two S's. Think: one Rude person causeS Stress.",
    example: "It is illegal to harass someone at work.",
    difficulty: "medium",
    monthlySearches: "30,000+",
  },
  {
    word: "hors d'oeuvre",
    misspellings: ["horderves", "ordeurves", "orderves", "hors doeuvres"],
    dialects: null,
    tip: "It's French. HORS (outside) + D'OEUVRE (the work). Appetizers served outside the main meal.",
    example: "They served hors d'oeuvres before dinner.",
    difficulty: "hard",
    monthlySearches: "20,000+",
  },
  {
    word: "independent",
    misspellings: ["independant", "independend", "indipendent", "indapendent"],
    dialects: null,
    tip: "Ends in DENT, not DANT. A DENT in dependence.",
    example: "She became financially independent at 25.",
    difficulty: "medium",
    monthlySearches: "50,000+",
  },
  {
    word: "jewelry",
    misspellings: ["jewellry", "jewlery", "jewelery", "jewlry"],
    dialects: { us: "jewelry", uk: "jewellery", au: "jewellery", nz: "jewellery" },
    tip: "US: JEWEL + RY. UK/AU/NZ: JEWEL + LERY.",
    example: "She wore her finest jewelry to the gala.",
    difficulty: "medium",
    monthlySearches: "25,000+",
  },
  {
    word: "knowledge",
    misspellings: ["knowlege", "knoledge", "knowlegde", "nowledge"],
    dialects: null,
    tip: "KNOW + LEDGE. Standing on the ledge of what you know.",
    example: "Knowledge is power.",
    difficulty: "easy",
    monthlySearches: "15,000+",
  },
  {
    word: "liaison",
    misspellings: ["liason", "liasion", "liaision", "leason"],
    dialects: null,
    tip: "Two I's: L-I-A-I-S-O-N. Think: I Always Irritate Spelling Obsessed Nerds.",
    example: "She serves as the liaison between the two departments.",
    difficulty: "hard",
    monthlySearches: "30,000+",
  },
  {
    word: "maintenance",
    misspellings: ["maintainance", "maintanence", "maintnance", "maintainence"],
    dialects: null,
    tip: "MAIN + TEN + ANCE. Not maintain + ance.",
    example: "Regular maintenance keeps the car running smoothly.",
    difficulty: "hard",
    monthlySearches: "60,000+",
  },
  {
    word: "millennium",
    misspellings: ["millenium", "milennium", "milleneum", "milenium"],
    dialects: null,
    tip: "Two L's and two N's. MILL + ENNIUM.",
    example: "The new millennium began in the year 2000.",
    difficulty: "hard",
    monthlySearches: "20,000+",
  },
  {
    word: "misspell",
    misspellings: ["mispell", "misspel", "mispel", "misspell"],
    dialects: null,
    tip: "MIS + SPELL. You need both S's. Ironic, isn't it?",
    example: "Don't misspell the client's name on the contract.",
    difficulty: "easy",
    monthlySearches: "257,000",
  },
  {
    word: "necessary",
    misspellings: ["neccessary", "necessery", "neccesary", "nesessary"],
    dialects: null,
    tip: "One C, two S's. A shirt has one Collar and two Sleeves.",
    example: "It is necessary to wear a helmet while cycling.",
    difficulty: "medium",
    monthlySearches: "60,000+",
  },
  {
    word: "occurrence",
    misspellings: ["occurence", "occurance", "occurrance", "ocurrence"],
    dialects: null,
    tip: "Two C's, two R's, then ENCE. Double trouble.",
    example: "This is an unusual occurrence.",
    difficulty: "hard",
    monthlySearches: "100,000+",
  },
  {
    word: "perseverance",
    misspellings: ["perserverance", "perseverence", "perseveranse", "perserverence"],
    dialects: null,
    tip: "PERSEVERE + ANCE. Sever is in the middle.",
    example: "Her perseverance paid off in the end.",
    difficulty: "hard",
    monthlySearches: "25,000+",
  },
  {
    word: "pharmaceutical",
    misspellings: ["farmaceutical", "pharmaseutical", "pharmeceutical", "pharmceutical"],
    dialects: null,
    tip: "PH not F. PHARMA + CEUTICAL.",
    example: "The pharmaceutical industry develops life-saving drugs.",
    difficulty: "hard",
    monthlySearches: "15,000+",
  },
  {
    word: "possession",
    misspellings: ["posession", "possesion", "posesion", "possestion"],
    dialects: null,
    tip: "Two S's, then two S's again. Double double S's.",
    example: "The stolen goods were found in his possession.",
    difficulty: "medium",
    monthlySearches: "15,000+",
  },
  {
    word: "privilege",
    misspellings: ["privelege", "priviledge", "privlege", "privilige"],
    dialects: null,
    tip: "No D. PRIVI + LEGE. It's a legal term (lege = law).",
    example: "Education is a privilege, not a right.",
    difficulty: "hard",
    monthlySearches: "40,000+",
  },
  {
    word: "pronunciation",
    misspellings: ["pronounciation", "pronuncation", "pronouncation", "prononsiation"],
    dialects: null,
    tip: "No OUNCE. It's PRONUNCI + ATION, not pronounce + ation.",
    example: "Her pronunciation of French words is excellent.",
    difficulty: "hard",
    monthlySearches: "30,000+",
  },
  {
    word: "quarantine",
    misspellings: ["quarentine", "quarintine", "quaranteen", "quarentene"],
    dialects: null,
    tip: "QUARAN + TINE. From the Italian quaranta (forty days).",
    example: "Travelers were placed in quarantine for two weeks.",
    difficulty: "medium",
    monthlySearches: "40,000+",
  },
  {
    word: "questionnaire",
    misspellings: ["questionaire", "questionairre", "questionnare", "questionair"],
    dialects: null,
    tip: "Two N's and ends in AIRE. QUESTION + NAIRE.",
    example: "Please fill out this questionnaire.",
    difficulty: "hard",
    monthlySearches: "30,000+",
  },
  {
    word: "receive",
    misspellings: ["recieve", "receve", "receave", "recive"],
    dialects: null,
    tip: "I before E except after C. reCEIve.",
    example: "You will receive a confirmation email shortly.",
    difficulty: "easy",
    monthlySearches: "80,000+",
  },
  {
    word: "recommend",
    misspellings: ["recomend", "reccommend", "reccomend", "recommand"],
    dialects: null,
    tip: "One C, two M's. Think: I recommend more M&Ms.",
    example: "I highly recommend this restaurant.",
    difficulty: "medium",
    monthlySearches: "30,000+",
  },
  {
    word: "restaurant",
    misspellings: ["restaraunt", "resturant", "restraunt", "resteraunt", "restrant"],
    dialects: null,
    tip: "REST + AU + RANT. You REST while someone rants about the AUbergine.",
    example: "The new restaurant downtown has great reviews.",
    difficulty: "medium",
    monthlySearches: "100,000+",
  },
  {
    word: "rhythm",
    misspellings: ["rythm", "rythym", "rhythym", "rithm"],
    dialects: null,
    tip: "Rhythm Has Your Two Hips Moving.",
    example: "The drummer kept a steady rhythm.",
    difficulty: "hard",
    monthlySearches: "50,000+",
  },
  {
    word: "schedule",
    misspellings: ["shedule", "scedule", "schedual", "schadule"],
    dialects: null,
    tip: "SCH at the start, like SCHOOL. SCHED + ULE.",
    example: "Check the schedule for meeting times.",
    difficulty: "medium",
    monthlySearches: "20,000+",
  },
  {
    word: "separate",
    misspellings: ["seperate", "seprate", "separete", "separet"],
    dialects: null,
    tip: "There's A RAT in sepARAte.",
    example: "Please separate the whites from the colors.",
    difficulty: "medium",
    monthlySearches: "100,000+",
  },
  {
    word: "supersede",
    misspellings: ["supercede", "superceed", "superseed", "superceed"],
    dialects: null,
    tip: "Ends in SEDE, not CEDE. It's the only English word that does.",
    example: "The new policy will supersede the old one.",
    difficulty: "hard",
    monthlySearches: "15,000+",
  },
  {
    word: "tomorrow",
    misspellings: ["tommorrow", "tommorow", "tomorow", "tommorrow"],
    dialects: null,
    tip: "One M, two R's. TOM + OR + ROW.",
    example: "We'll finish the project tomorrow.",
    difficulty: "easy",
    monthlySearches: "30,000+",
  },
  {
    word: "vacuum",
    misspellings: ["vaccum", "vacume", "vaccuum", "vacum"],
    dialects: null,
    tip: "One C, two U's. The vacuum sucks up U's.",
    example: "Please vacuum the living room before guests arrive.",
    difficulty: "medium",
    monthlySearches: "25,000+",
  },
  {
    word: "weird",
    misspellings: ["wierd", "weerd", "wird", "werid"],
    dialects: null,
    tip: "WE are WEIRD. E before I. It breaks the rule, because it's weird.",
    example: "That was a weird coincidence.",
    difficulty: "easy",
    monthlySearches: "15,000+",
  },
  // Batch 2 - 50 words
  {
    word: "absence",
    misspellings: ["absense", "abscence", "absance", "abcense"],
    dialects: null,
    tip: "Ends in ENCE, not ENSE. Think: ABSENT + CE.",
    example: "Her absence from the meeting was noted.",
    difficulty: "medium",
    monthlySearches: "12,000+",
  },
  {
    word: "accessible",
    misspellings: ["accessable", "acessible", "accesible", "accessibile"],
    dialects: null,
    tip: "Two C's, two S's, ends in IBLE not ABLE.",
    example: "The building is wheelchair accessible.",
    difficulty: "hard",
    monthlySearches: "15,000+",
  },
  {
    word: "aggressive",
    misspellings: ["agressive", "aggresive", "agresive", "aggrssive"],
    dialects: null,
    tip: "Two G's and two S's. Double the aggression.",
    example: "The dog became aggressive when approached.",
    difficulty: "medium",
    monthlySearches: "18,000+",
  },
  {
    word: "amateur",
    misspellings: ["amature", "amatuer", "amater", "amateure"],
    dialects: null,
    tip: "Ends in EUR, the French way. Not TURE.",
    example: "He competed as an amateur boxer.",
    difficulty: "medium",
    monthlySearches: "12,000+",
  },
  {
    word: "anonymous",
    misspellings: ["anonomous", "anonimous", "anonymus", "annonymous"],
    dialects: null,
    tip: "A-NON-Y-MOUS. Think: A NONentity who is mYsterious.",
    example: "The donation was made by an anonymous benefactor.",
    difficulty: "medium",
    monthlySearches: "10,000+",
  },
  {
    word: "argument",
    misspellings: ["arguement", "arguemant", "argumant", "arguemnt"],
    dialects: null,
    tip: "No E after ARGU. The E from argue is dropped.",
    example: "They had a heated argument about politics.",
    difficulty: "easy",
    monthlySearches: "20,000+",
  },
  {
    word: "atheist",
    misspellings: ["athiest", "athist", "atheest", "athieist"],
    dialects: null,
    tip: "E before I. THE is hiding inside: aTHEist.",
    example: "He identifies as an atheist.",
    difficulty: "medium",
    monthlySearches: "8,000+",
  },
  {
    word: "beginning",
    misspellings: ["begining", "begginning", "beggining", "beginng"],
    dialects: null,
    tip: "Double N in the middle. BEGIN + NING.",
    example: "This is just the beginning of our journey.",
    difficulty: "easy",
    monthlySearches: "25,000+",
  },
  {
    word: "bizarre",
    misspellings: ["bizzare", "bizare", "bizzar", "bazaar"],
    dialects: null,
    tip: "One Z, double R. Think: it's biZarre with two R's.",
    example: "The painting depicted a bizarre landscape.",
    difficulty: "medium",
    monthlySearches: "12,000+",
  },
  {
    word: "camouflage",
    misspellings: ["camoflage", "camoflague", "camoflauge", "camoflaj"],
    dialects: null,
    tip: "OU in the middle, AGE at the end. CAM + OU + FLAGE.",
    example: "Soldiers wear camouflage to blend in.",
    difficulty: "hard",
    monthlySearches: "15,000+",
  },
  {
    word: "changeable",
    misspellings: ["changable", "changeble", "changabel", "changebale"],
    dialects: null,
    tip: "Keep the E from change. CHANGE + ABLE.",
    example: "British weather is notoriously changeable.",
    difficulty: "medium",
    monthlySearches: "8,000+",
  },
  {
    word: "collectible",
    misspellings: ["collectable", "colectable", "collectabel", "collectibel"],
    dialects: { us: "collectible", uk: "collectable", au: "collectable", nz: "collectable" },
    tip: "US uses IBLE, UK uses ABLE. Both are accepted.",
    example: "Vintage toys are highly collectible items.",
    difficulty: "medium",
    monthlySearches: "10,000+",
  },
  {
    word: "committed",
    misspellings: ["commited", "comitted", "comited", "committeed"],
    dialects: null,
    tip: "Double M, double T. COMMIT + TED.",
    example: "She is committed to finishing the project.",
    difficulty: "medium",
    monthlySearches: "15,000+",
  },
  {
    word: "consensus",
    misspellings: ["concensus", "consencus", "concensous", "consensous"],
    dialects: null,
    tip: "CON + SENSUS. No C in the middle part.",
    example: "The team reached a consensus on the plan.",
    difficulty: "hard",
    monthlySearches: "12,000+",
  },
  {
    word: "copyright",
    misspellings: ["copywrite", "copywright", "copright", "copywrit"],
    dialects: null,
    tip: "COPY + RIGHT, not WRITE. It's about your right to copy.",
    example: "The image is protected by copyright.",
    difficulty: "medium",
    monthlySearches: "10,000+",
  },
  {
    word: "curiosity",
    misspellings: ["curiousity", "curosity", "curiosety", "curiocity"],
    dialects: null,
    tip: "Drop the OU from curious. CURIOS + ITY.",
    example: "Curiosity killed the cat.",
    difficulty: "medium",
    monthlySearches: "10,000+",
  },
  {
    word: "desirable",
    misspellings: ["desireable", "desirible", "desirabel", "desirble"],
    dialects: null,
    tip: "Drop the E from desire. DESIR + ABLE.",
    example: "A quiet location makes the house more desirable.",
    difficulty: "medium",
    monthlySearches: "8,000+",
  },
  {
    word: "desperate",
    misspellings: ["desparate", "despirate", "desprate", "desperite"],
    dialects: null,
    tip: "PER in the middle, not PAR. DESPER + ATE.",
    example: "They were desperate for help.",
    difficulty: "medium",
    monthlySearches: "15,000+",
  },
  {
    word: "develop",
    misspellings: ["develope", "develp", "devlop", "develoep"],
    dialects: null,
    tip: "No E at the end. DEVELOP, not develope.",
    example: "They plan to develop the software further.",
    difficulty: "easy",
    monthlySearches: "12,000+",
  },
  {
    word: "difference",
    misspellings: ["diffrence", "diference", "differance", "differense"],
    dialects: null,
    tip: "Two F's, ends in ENCE. DIFFER + ENCE.",
    example: "Can you spot the difference?",
    difficulty: "easy",
    monthlySearches: "12,000+",
  },
  {
    word: "entrepreneur",
    misspellings: ["entrepeneur", "entreprenur", "entreprener", "entrapreneur"],
    dialects: null,
    tip: "ENTRE + PRE + NEUR. A French word meaning undertaker (of business).",
    example: "She became a successful entrepreneur at 30.",
    difficulty: "hard",
    monthlySearches: "25,000+",
  },
  {
    word: "experience",
    misspellings: ["expierence", "experiance", "expirence", "experence"],
    dialects: null,
    tip: "PER then I then ENCE. exPERIENCE.",
    example: "She has ten years of experience.",
    difficulty: "medium",
    monthlySearches: "18,000+",
  },
  {
    word: "fascinate",
    misspellings: ["facinate", "fascenate", "fasinate", "fasscinate"],
    dialects: null,
    tip: "SC in the middle, like SCIENCE. FA + SCI + NATE.",
    example: "Ancient history continues to fascinate scholars.",
    difficulty: "medium",
    monthlySearches: "10,000+",
  },
  {
    word: "fiery",
    misspellings: ["firey", "firy", "firey", "fierey"],
    dialects: null,
    tip: "FIRE becomes FIER + Y. The E moves before the R.",
    example: "The sunset painted the sky in fiery colors.",
    difficulty: "medium",
    monthlySearches: "8,000+",
  },
  {
    word: "fluorescent",
    misspellings: ["flourescent", "florescent", "fluourescent", "fluoresent"],
    dialects: null,
    tip: "FLUOR + ESCENT. Think fluoride.",
    example: "The office had harsh fluorescent lighting.",
    difficulty: "hard",
    monthlySearches: "12,000+",
  },
  {
    word: "forty",
    misspellings: ["fourty", "fourtie", "fortey", "fortie"],
    dialects: null,
    tip: "No U. Four has a U, but forty does not.",
    example: "She celebrated her forty-fifth birthday.",
    difficulty: "easy",
    monthlySearches: "20,000+",
  },
  {
    word: "friend",
    misspellings: ["freind", "frend", "freand", "frind"],
    dialects: null,
    tip: "I before E. FRI + END. A friend to the end.",
    example: "She is my closest friend.",
    difficulty: "easy",
    monthlySearches: "15,000+",
  },
  {
    word: "grammar",
    misspellings: ["grammer", "gramer", "gramar", "grammor"],
    dialects: null,
    tip: "Ends in AR, not ER. GRAMM + AR.",
    example: "Good grammar makes writing clearer.",
    difficulty: "easy",
    monthlySearches: "25,000+",
  },
  {
    word: "grateful",
    misspellings: ["greatful", "gratefull", "greatfull", "graitful"],
    dialects: null,
    tip: "GRATE + FUL. One L. It's grate, not great.",
    example: "I am grateful for your help.",
    difficulty: "easy",
    monthlySearches: "20,000+",
  },
  {
    word: "height",
    misspellings: ["heighth", "hieght", "heigth", "hight"],
    dialects: null,
    tip: "No TH at the end. HEIGHT, not heighth. EI not IE.",
    example: "What is the height of that building?",
    difficulty: "easy",
    monthlySearches: "12,000+",
  },
  {
    word: "hierarchy",
    misspellings: ["heirarchy", "heirachy", "hierarcy", "hierachy"],
    dialects: null,
    tip: "HIER + ARCHY. I before E, then ARCHY (rule).",
    example: "The company has a strict hierarchy.",
    difficulty: "hard",
    monthlySearches: "15,000+",
  },
  {
    word: "humorous",
    misspellings: ["humourous", "humerous", "humorus", "humurous"],
    dialects: { us: "humorous", uk: "humourous", au: "humourous", nz: "humourous" },
    tip: "US: humorous. UK/AU/NZ: humourous (with U).",
    example: "The speech was both informative and humorous.",
    difficulty: "medium",
    monthlySearches: "10,000+",
  },
  {
    word: "hygiene",
    misspellings: ["hygeine", "hygine", "hygene", "hygeiene"],
    dialects: null,
    tip: "I before E. HYG + IENE.",
    example: "Good hygiene prevents the spread of disease.",
    difficulty: "medium",
    monthlySearches: "15,000+",
  },
  {
    word: "ignorance",
    misspellings: ["ignorence", "ignoranse", "ignorince", "ignerance"],
    dialects: null,
    tip: "Ends in ANCE, not ENCE. IGNOR + ANCE.",
    example: "Ignorance of the law is no excuse.",
    difficulty: "medium",
    monthlySearches: "10,000+",
  },
  {
    word: "immediately",
    misspellings: ["immediatly", "imediately", "immedietly", "immeadiatly"],
    dialects: null,
    tip: "IMMEDIATE + LY. Don't drop the E.",
    example: "Please respond immediately.",
    difficulty: "medium",
    monthlySearches: "20,000+",
  },
  {
    word: "intelligence",
    misspellings: ["inteligence", "intellegence", "inteligance", "intelligance"],
    dialects: null,
    tip: "Two L's, ends in ENCE. INTELLI + GENCE.",
    example: "Artificial intelligence is changing the world.",
    difficulty: "medium",
    monthlySearches: "15,000+",
  },
  {
    word: "interesting",
    misspellings: ["intresting", "intersting", "intressting", "interasting"],
    dialects: null,
    tip: "INTEREST + ING. Don't drop the second E.",
    example: "That was an interesting lecture.",
    difficulty: "easy",
    monthlySearches: "12,000+",
  },
  {
    word: "irresistible",
    misspellings: ["irresistable", "iresistible", "irresistabel", "irresistble"],
    dialects: null,
    tip: "Ends in IBLE, not ABLE. IR + RESIST + IBLE.",
    example: "The chocolate cake was irresistible.",
    difficulty: "hard",
    monthlySearches: "10,000+",
  },
  {
    word: "jealous",
    misspellings: ["jellous", "jelous", "jealus", "jealouse"],
    dialects: null,
    tip: "JEAL + OUS. Think: ZEAL with a J.",
    example: "He was jealous of her success.",
    difficulty: "easy",
    monthlySearches: "12,000+",
  },
  {
    word: "length",
    misspellings: ["lenght", "lenth", "lentgh", "langth"],
    dialects: null,
    tip: "LENG + TH. The G comes before the T.",
    example: "The length of the bridge is two miles.",
    difficulty: "easy",
    monthlySearches: "10,000+",
  },
  {
    word: "library",
    misspellings: ["libary", "liberry", "libery", "librairy"],
    dialects: null,
    tip: "Two R's. LI + BRAR + Y.",
    example: "She borrowed the book from the library.",
    difficulty: "easy",
    monthlySearches: "15,000+",
  },
  {
    word: "loneliness",
    misspellings: ["lonelyness", "lonlyness", "lonliness", "lonelines"],
    dialects: null,
    tip: "LONELY drops the Y, adds INESS. LONELI + NESS.",
    example: "Loneliness is a common problem among seniors.",
    difficulty: "medium",
    monthlySearches: "10,000+",
  },
  {
    word: "medieval",
    misspellings: ["medeval", "medeival", "medievel", "mideval"],
    dialects: null,
    tip: "MEDI + EVAL. Think: the middle eval(uation) of history.",
    example: "The castle dates back to medieval times.",
    difficulty: "hard",
    monthlySearches: "12,000+",
  },
  {
    word: "miniature",
    misspellings: ["minature", "miniture", "mineature", "minaiture"],
    dialects: null,
    tip: "MINI + ATURE. There's an I after the N and before the A.",
    example: "She collects miniature figurines.",
    difficulty: "medium",
    monthlySearches: "10,000+",
  },
  {
    word: "mischievous",
    misspellings: ["mischevious", "mischevous", "mischievious", "mischeivous"],
    dialects: null,
    tip: "No I after the V. MIS + CHIE + VOUS.",
    example: "The mischievous puppy chewed up the shoes.",
    difficulty: "hard",
    monthlySearches: "10,000+",
  },
  {
    word: "noticeable",
    misspellings: ["noticable", "notisable", "noticible", "notiecable"],
    dialects: null,
    tip: "Keep the E from notice. NOTICE + ABLE.",
    example: "There was a noticeable improvement in her grades.",
    difficulty: "medium",
    monthlySearches: "10,000+",
  },
  {
    word: "occasion",
    misspellings: ["occassion", "ocasion", "ocassion", "occation"],
    dialects: null,
    tip: "Two C's, one S. Think: two coats for the occasion.",
    example: "It was a special occasion for the family.",
    difficulty: "medium",
    monthlySearches: "15,000+",
  },
  {
    word: "pastime",
    misspellings: ["passtime", "pasttime", "past time", "pasttme"],
    dialects: null,
    tip: "One S. PAST + TIME, but only one S when combined.",
    example: "Reading is my favorite pastime.",
    difficulty: "medium",
    monthlySearches: "8,000+",
  },
  {
    word: "perceive",
    misspellings: ["percieve", "perceve", "persieve", "preceive"],
    dialects: null,
    tip: "I before E except after C. perCEIve.",
    example: "How you perceive the world shapes your reality.",
    difficulty: "medium",
    monthlySearches: "10,000+",
  },
  {
    word: "personnel",
    misspellings: ["personel", "personell", "perssonel", "personnell"],
    dialects: null,
    tip: "Two N's, one L. PERSON + NEL.",
    example: "The personnel department handles hiring.",
    difficulty: "medium",
    monthlySearches: "10,000+",
  },
  // Batch 3 - 100 words
  {
    word: "acquaintance",
    misspellings: ["acquaintence", "aquaintance", "acquantance", "acquaintanse"],
    dialects: null,
    tip: "ACQ + UAINT + ANCE. Don't forget the C after A.",
    example: "She is an acquaintance from work.",
    difficulty: "hard",
    monthlySearches: "12,000+",
  },
  {
    word: "adequate",
    misspellings: ["adaquate", "adequete", "addequate", "adequite"],
    dialects: null,
    tip: "AD + EQUATE. Think: is it equal to the task?",
    example: "The lighting was barely adequate for reading.",
    difficulty: "medium",
    monthlySearches: "10,000+",
  },
  {
    word: "advantageous",
    misspellings: ["advantagous", "advantageus", "advantagious", "advantageos"],
    dialects: null,
    tip: "Keep the E from advantage. ADVANTAGE + OUS.",
    example: "Being bilingual is advantageous in business.",
    difficulty: "hard",
    monthlySearches: "8,000+",
  },
  {
    word: "analyses",
    misspellings: ["analysies", "analyzes", "analises", "analysees"],
    dialects: { us: "analyses", uk: "analyses", au: "analyses", nz: "analyses" },
    tip: "Plural of analysis. The IS becomes ES.",
    example: "The lab ran multiple analyses on the samples.",
    difficulty: "medium",
    monthlySearches: "8,000+",
  },
  {
    word: "ancient",
    misspellings: ["anciant", "anchient", "anceint", "aincient"],
    dialects: null,
    tip: "I before E. ANC + IENT.",
    example: "The ancient ruins attracted many tourists.",
    difficulty: "easy",
    monthlySearches: "10,000+",
  },
  {
    word: "anxiety",
    misspellings: ["anxeity", "anxiaty", "anxity", "anixety"],
    dialects: null,
    tip: "ANX + I + ETY. The I sits between X and E.",
    example: "She experiences anxiety before public speaking.",
    difficulty: "medium",
    monthlySearches: "20,000+",
  },
  {
    word: "apparent",
    misspellings: ["apparant", "aparent", "apparrent", "appairent"],
    dialects: null,
    tip: "Two P's, ends in ENT not ANT. AP + PARENT.",
    example: "The answer was apparent to everyone.",
    difficulty: "medium",
    monthlySearches: "12,000+",
  },
  {
    word: "appreciate",
    misspellings: ["appriciate", "apreciate", "appreciete", "apprecate"],
    dialects: null,
    tip: "Two P's, then PRECI. AP + PRECI + ATE.",
    example: "I really appreciate your help.",
    difficulty: "medium",
    monthlySearches: "15,000+",
  },
  {
    word: "appropriate",
    misspellings: ["apropriate", "appopriate", "appropreate", "appropriet"],
    dialects: null,
    tip: "Two P's at the start. AP + PROPRI + ATE.",
    example: "Please wear appropriate clothing.",
    difficulty: "medium",
    monthlySearches: "12,000+",
  },
  {
    word: "assassination",
    misspellings: ["assasination", "assassanation", "asassination", "assasanation"],
    dialects: null,
    tip: "Four S's total. ASS + ASS + IN + ATION.",
    example: "The assassination shocked the nation.",
    difficulty: "hard",
    monthlySearches: "8,000+",
  },
  {
    word: "authentic",
    misspellings: ["authentik", "authintic", "authentc", "authantic"],
    dialects: null,
    tip: "AUTH + ENT + IC. Think: the author is authentic.",
    example: "The painting was confirmed as authentic.",
    difficulty: "medium",
    monthlySearches: "10,000+",
  },
  {
    word: "bankruptcy",
    misspellings: ["bankrupcy", "bankruptsy", "banckruptcy", "bankruptcy"],
    dialects: null,
    tip: "BANK + RUPT + CY. The T before CY is easy to miss.",
    example: "The company filed for bankruptcy.",
    difficulty: "hard",
    monthlySearches: "12,000+",
  },
  {
    word: "boundary",
    misspellings: ["boundry", "boundery", "boundrary", "boudary"],
    dialects: null,
    tip: "BOUND + ARY. Don't forget the A.",
    example: "The river marks the boundary between the two states.",
    difficulty: "medium",
    monthlySearches: "8,000+",
  },
  {
    word: "broccoli",
    misspellings: ["brocoli", "brocolli", "broccilli", "broccolli"],
    dialects: null,
    tip: "Two C's, one L. BROCC + OLI.",
    example: "Steamed broccoli is a healthy side dish.",
    difficulty: "medium",
    monthlySearches: "15,000+",
  },
  {
    word: "cantaloupe",
    misspellings: ["cantalope", "cantaloup", "canteloupe", "cantaloup"],
    dialects: null,
    tip: "CANTA + LOUPE. Ends in OUPE.",
    example: "Fresh cantaloupe is perfect for summer.",
    difficulty: "hard",
    monthlySearches: "8,000+",
  },
  {
    word: "category",
    misspellings: ["catagory", "catigory", "categery", "categorie"],
    dialects: null,
    tip: "E in the middle, not A. CAT + EGOR + Y.",
    example: "This product falls into a new category.",
    difficulty: "medium",
    monthlySearches: "10,000+",
  },
  {
    word: "cauliflower",
    misspellings: ["colliflower", "cauliflour", "cauliflowere", "cauliflwoer"],
    dialects: null,
    tip: "CAULI + FLOWER. It's a flower made of caulis (stems).",
    example: "Roasted cauliflower makes a great side dish.",
    difficulty: "medium",
    monthlySearches: "10,000+",
  },
  {
    word: "challenge",
    misspellings: ["challange", "chalenge", "chalange", "challange"],
    dialects: null,
    tip: "Two L's, ends in ENGE not ANGE. CHALL + ENGE.",
    example: "The project was a real challenge.",
    difficulty: "easy",
    monthlySearches: "12,000+",
  },
  {
    word: "characteristic",
    misspellings: ["charachteristic", "characteristik", "charecteristic", "characterisitc"],
    dialects: null,
    tip: "CHARACTER + ISTIC. Spell character first.",
    example: "Patience is her most admirable characteristic.",
    difficulty: "hard",
    monthlySearches: "8,000+",
  },
  {
    word: "coincidence",
    misspellings: ["coincedence", "coincidense", "coinsidence", "coincidance"],
    dialects: null,
    tip: "CO + INCID + ENCE. Think: an incident that co-occurs.",
    example: "Meeting her there was a complete coincidence.",
    difficulty: "medium",
    monthlySearches: "10,000+",
  },
  {
    word: "comfortable",
    misspellings: ["comfertable", "comftable", "comfortble", "confortable"],
    dialects: null,
    tip: "COMFORT + ABLE. Don't skip the ORT.",
    example: "The new sofa is very comfortable.",
    difficulty: "easy",
    monthlySearches: "15,000+",
  },
  {
    word: "committee",
    misspellings: ["commitee", "comittee", "comitee", "committy"],
    dialects: null,
    tip: "Double M, double T, double E. Three doubles.",
    example: "The committee will meet on Thursday.",
    difficulty: "medium",
    monthlySearches: "12,000+",
  },
  {
    word: "communicate",
    misspellings: ["comunicate", "comminucate", "communcate", "communikate"],
    dialects: null,
    tip: "Two M's. COMMUNI + CATE.",
    example: "It's important to communicate clearly.",
    difficulty: "medium",
    monthlySearches: "10,000+",
  },
  {
    word: "competition",
    misspellings: ["competion", "compitition", "competiton", "competision"],
    dialects: null,
    tip: "COMPETI + TION. Don't forget the second I.",
    example: "The competition was fierce this year.",
    difficulty: "medium",
    monthlySearches: "10,000+",
  },
  {
    word: "completely",
    misspellings: ["completly", "completley", "compleatly", "completally"],
    dialects: null,
    tip: "COMPLETE + LY. Keep the E.",
    example: "I completely forgot about the meeting.",
    difficulty: "easy",
    monthlySearches: "8,000+",
  },
  {
    word: "concentrate",
    misspellings: ["concetrate", "concentrait", "consintrate", "consentrate"],
    dialects: null,
    tip: "CON + CENTR + ATE. Center is in the middle.",
    example: "I need quiet to concentrate on my work.",
    difficulty: "medium",
    monthlySearches: "8,000+",
  },
  {
    word: "confident",
    misspellings: ["confidant", "confadent", "confedent", "confindent"],
    dialects: null,
    tip: "Ends in ENT (adjective). CONFIDANT is a different word (a person you confide in).",
    example: "She felt confident before the interview.",
    difficulty: "medium",
    monthlySearches: "10,000+",
  },
  {
    word: "consequence",
    misspellings: ["consequense", "consequance", "concequence", "consequince"],
    dialects: null,
    tip: "CONSE + QUENCE. Think: a question (QU) about what follows.",
    example: "Every action has a consequence.",
    difficulty: "medium",
    monthlySearches: "10,000+",
  },
  {
    word: "contemporary",
    misspellings: ["contempory", "contemporery", "contemparary", "contemprary"],
    dialects: null,
    tip: "CON + TEMPOR + ARY. TEMPOR (time) is in the middle.",
    example: "She enjoys contemporary art.",
    difficulty: "hard",
    monthlySearches: "8,000+",
  },
  {
    word: "controversial",
    misspellings: ["contraversial", "controversal", "contreversial", "controvercial"],
    dialects: null,
    tip: "CONTROVER + SIAL. Not CONTRA.",
    example: "The decision proved controversial.",
    difficulty: "hard",
    monthlySearches: "10,000+",
  },
  {
    word: "convenience",
    misspellings: ["convienence", "conveniance", "conveinence", "conveenience"],
    dialects: null,
    tip: "CON + VENI + ENCE. VENI (come) is Latin.",
    example: "The store is open for your convenience.",
    difficulty: "medium",
    monthlySearches: "10,000+",
  },
  {
    word: "correlation",
    misspellings: ["corelation", "correllation", "corolation", "corelasion"],
    dialects: null,
    tip: "Two R's, one L. COR + RELAT + ION.",
    example: "There is a correlation between exercise and health.",
    difficulty: "hard",
    monthlySearches: "8,000+",
  },
  {
    word: "courageous",
    misspellings: ["couragous", "corageous", "curageous", "courageouse"],
    dialects: null,
    tip: "Keep the E from courage. COURAGE + OUS.",
    example: "It was a courageous act of bravery.",
    difficulty: "medium",
    monthlySearches: "8,000+",
  },
  {
    word: "criticism",
    misspellings: ["critisism", "critisicm", "criticizm", "criticisum"],
    dialects: null,
    tip: "CRITIC + ISM. Two I's separated by C's.",
    example: "Constructive criticism helps us improve.",
    difficulty: "medium",
    monthlySearches: "10,000+",
  },
  {
    word: "deceive",
    misspellings: ["decieve", "deceave", "deceve", "desieve"],
    dialects: null,
    tip: "I before E except after C. deCEIve.",
    example: "Appearances can deceive you.",
    difficulty: "medium",
    monthlySearches: "10,000+",
  },
  {
    word: "decision",
    misspellings: ["desicion", "decission", "decistion", "decison"],
    dialects: null,
    tip: "DECI + SION. One S only.",
    example: "Making the right decision takes courage.",
    difficulty: "easy",
    monthlySearches: "12,000+",
  },
  {
    word: "democracy",
    misspellings: ["democrasy", "democrocy", "democrecy", "demacracy"],
    dialects: null,
    tip: "DEMO + CRACY. People (demos) + rule (kratos).",
    example: "Democracy requires an informed citizenry.",
    difficulty: "medium",
    monthlySearches: "10,000+",
  },
  {
    word: "diaphragm",
    misspellings: ["diaphram", "diafragm", "diaphragam", "diaphram"],
    dialects: null,
    tip: "DIA + PHRAGM. The PH makes an F sound.",
    example: "Singers learn to breathe using their diaphragm.",
    difficulty: "hard",
    monthlySearches: "8,000+",
  },
  {
    word: "discipline",
    misspellings: ["disipline", "disiplin", "dicipline", "disapline"],
    dialects: null,
    tip: "DISC + IP + LINE. A disc on the line.",
    example: "Self-discipline is key to success.",
    difficulty: "medium",
    monthlySearches: "12,000+",
  },
  {
    word: "drought",
    misspellings: ["drout", "drougt", "drowt", "drougth"],
    dialects: null,
    tip: "Ends in OUGHT, like thought and bought.",
    example: "The drought lasted for three months.",
    difficulty: "medium",
    monthlySearches: "10,000+",
  },
  {
    word: "eighth",
    misspellings: ["eigth", "eightth", "eighth", "eitgh"],
    dialects: null,
    tip: "EIGHT + H. Just add H to eight.",
    example: "She finished in eighth place.",
    difficulty: "easy",
    monthlySearches: "10,000+",
  },
  {
    word: "eligible",
    misspellings: ["eligable", "elegible", "elligible", "elgible"],
    dialects: null,
    tip: "Ends in IBLE, not ABLE. ELIG + IBLE.",
    example: "You must be 18 to be eligible to vote.",
    difficulty: "medium",
    monthlySearches: "10,000+",
  },
  {
    word: "eloquent",
    misspellings: ["eloquant", "elloquent", "elequent", "eloquint"],
    dialects: null,
    tip: "ELO + QUENT. One L only.",
    example: "She gave an eloquent speech.",
    difficulty: "medium",
    monthlySearches: "8,000+",
  },
  {
    word: "enthusiasm",
    misspellings: ["enthusiam", "enthisiasm", "enthusiasim", "entheusiasm"],
    dialects: null,
    tip: "EN + THUSI + ASM. THUS is hiding inside.",
    example: "His enthusiasm for the project was contagious.",
    difficulty: "medium",
    monthlySearches: "10,000+",
  },
  {
    word: "especially",
    misspellings: ["expecially", "esspecially", "especally", "especialy"],
    dialects: null,
    tip: "Starts with ESP, not EXP. ESP + ECI + ALLY.",
    example: "I love all fruit, especially strawberries.",
    difficulty: "easy",
    monthlySearches: "15,000+",
  },
  {
    word: "exhilarate",
    misspellings: ["exhilerate", "exhilorate", "exhilerate", "exhilirate"],
    dialects: null,
    tip: "EX + HILAR + ATE. HILAR (cheerful) is in the middle.",
    example: "The roller coaster ride was exhilarating.",
    difficulty: "hard",
    monthlySearches: "6,000+",
  },
  {
    word: "extraordinary",
    misspellings: ["extrordinary", "extraodinary", "extraordinery", "extrordinary"],
    dialects: null,
    tip: "EXTRA + ORDINARY. Beyond the ordinary.",
    example: "She has an extraordinary talent for music.",
    difficulty: "medium",
    monthlySearches: "10,000+",
  },
  {
    word: "feasible",
    misspellings: ["feasable", "feesible", "feasibile", "feasble"],
    dialects: null,
    tip: "Ends in IBLE, not ABLE. FEAS + IBLE.",
    example: "The plan is technically feasible.",
    difficulty: "medium",
    monthlySearches: "8,000+",
  },
  {
    word: "February",
    misspellings: ["Febuary", "Feburary", "Febrary", "Febraury"],
    dialects: null,
    tip: "Two R's. FEB + RU + ARY. Don't drop the first R.",
    example: "Valentine's Day is in February.",
    difficulty: "easy",
    monthlySearches: "30,000+",
  },
  {
    word: "genuine",
    misspellings: ["geniune", "genuene", "geniuine", "genuin"],
    dialects: null,
    tip: "GEN + U + INE. U before I.",
    example: "Is this a genuine antique?",
    difficulty: "medium",
    monthlySearches: "10,000+",
  },
  {
    word: "grievance",
    misspellings: ["greivance", "grievence", "grievanse", "greivence"],
    dialects: null,
    tip: "I before E. GRIEV + ANCE.",
    example: "She filed a formal grievance with HR.",
    difficulty: "medium",
    monthlySearches: "8,000+",
  },
  {
    word: "handkerchief",
    misspellings: ["hankerchief", "handkerchif", "handkercheif", "hankerchif"],
    dialects: null,
    tip: "HAND + KERCHIEF. A hand cloth (kerchief).",
    example: "He offered her his handkerchief.",
    difficulty: "hard",
    monthlySearches: "8,000+",
  },
  {
    word: "hemorrhage",
    misspellings: ["hemorage", "hemorrage", "hemmorhage", "hemorrhadge"],
    dialects: { us: "hemorrhage", uk: "haemorrhage", au: "haemorrhage", nz: "haemorrhage" },
    tip: "Two R's in the middle. HEMO + RRHAGE.",
    example: "The patient suffered a hemorrhage during surgery.",
    difficulty: "hard",
    monthlySearches: "10,000+",
  },
  {
    word: "identify",
    misspellings: ["indentify", "identefy", "identifie", "idintify"],
    dialects: null,
    tip: "IDENT + IFY. Think: ID + ENTITY.",
    example: "Can you identify the suspect?",
    difficulty: "easy",
    monthlySearches: "10,000+",
  },
  {
    word: "illegitimate",
    misspellings: ["ilegitimate", "illegitamate", "illegitemate", "illegitamit"],
    dialects: null,
    tip: "Two L's. IL + LEGITIMATE.",
    example: "The court ruled the contract illegitimate.",
    difficulty: "hard",
    monthlySearches: "6,000+",
  },
  {
    word: "incidentally",
    misspellings: ["incidently", "incidentaly", "incedentally", "insidentally"],
    dialects: null,
    tip: "INCIDENTAL + LY. Keep the AL before LY.",
    example: "Incidentally, I found your keys on the table.",
    difficulty: "medium",
    monthlySearches: "6,000+",
  },
  {
    word: "inevitable",
    misspellings: ["inevitible", "inevatable", "inevidable", "inevitabel"],
    dialects: null,
    tip: "IN + EVIT + ABLE. Think: you can't evict the inevitable.",
    example: "Change is inevitable.",
    difficulty: "medium",
    monthlySearches: "10,000+",
  },
  {
    word: "influential",
    misspellings: ["influencial", "influental", "influenctial", "influensial"],
    dialects: null,
    tip: "INFLUENT + IAL. Not ENCIAL.",
    example: "She is one of the most influential leaders.",
    difficulty: "medium",
    monthlySearches: "8,000+",
  },
  {
    word: "inoculate",
    misspellings: ["innoculate", "inoculate", "innoculate", "inocculate"],
    dialects: null,
    tip: "One N, one C. IN + OCULATE.",
    example: "They plan to inoculate the entire population.",
    difficulty: "hard",
    monthlySearches: "8,000+",
  },
  {
    word: "itinerary",
    misspellings: ["itinery", "itinenary", "itinarary", "itenerery"],
    dialects: null,
    tip: "ITINER + ARY. Think: I TIN ER ARY.",
    example: "What's on the travel itinerary for tomorrow?",
    difficulty: "hard",
    monthlySearches: "12,000+",
  },
  {
    word: "legitimate",
    misspellings: ["legitmate", "legitamate", "legitemate", "lagitimate"],
    dialects: null,
    tip: "LEGIT + IMATE. Keep it legit.",
    example: "Is this a legitimate business?",
    difficulty: "medium",
    monthlySearches: "10,000+",
  },
  {
    word: "lieutenant",
    misspellings: ["leutenant", "leiutenant", "lieutenent", "luietenant"],
    dialects: null,
    tip: "LIEU + TENANT. A place-holder (tenant of a lieu/place).",
    example: "The lieutenant commanded the platoon.",
    difficulty: "hard",
    monthlySearches: "10,000+",
  },
  {
    word: "magnificent",
    misspellings: ["magnificant", "magnificient", "magnifecent", "magnificint"],
    dialects: null,
    tip: "Ends in CENT, not CANT. MAGNIFI + CENT.",
    example: "The view from the mountain was magnificent.",
    difficulty: "medium",
    monthlySearches: "8,000+",
  },
  {
    word: "maneuver",
    misspellings: ["manuever", "manoever", "manouver", "manuver"],
    dialects: { us: "maneuver", uk: "manoeuvre", au: "manoeuvre", nz: "manoeuvre" },
    tip: "US: MAN + EU + VER. UK: MAN + OEU + VRE.",
    example: "The pilot executed a difficult maneuver.",
    difficulty: "hard",
    monthlySearches: "12,000+",
  },
  {
    word: "miscellaneous",
    misspellings: ["miscelaneous", "miscellanious", "miscellanous", "miscellaneus"],
    dialects: null,
    tip: "Two L's, ends in EOUS. MISCELL + ANEOUS.",
    example: "There was a box of miscellaneous items.",
    difficulty: "hard",
    monthlySearches: "10,000+",
  },
  {
    word: "mortgage",
    misspellings: ["morgage", "morgadge", "mortage", "mortgadge"],
    dialects: null,
    tip: "MORT (death) + GAGE (pledge). A death pledge.",
    example: "They took out a 30-year mortgage.",
    difficulty: "medium",
    monthlySearches: "15,000+",
  },
  {
    word: "negotiate",
    misspellings: ["negociate", "negotiete", "negotaite", "negoiate"],
    dialects: null,
    tip: "NEGOTI + ATE. Think: NOT + I + ATE (go).",
    example: "They will negotiate the terms of the contract.",
    difficulty: "medium",
    monthlySearches: "10,000+",
  },
  {
    word: "ninety",
    misspellings: ["ninty", "ninteen", "ninety", "niney"],
    dialects: null,
    tip: "NINE + TY. Keep the E from nine.",
    example: "My grandmother is ninety years old.",
    difficulty: "easy",
    monthlySearches: "10,000+",
  },
  {
    word: "obedience",
    misspellings: ["obediance", "obideince", "obedience", "obedience"],
    dialects: null,
    tip: "Ends in IENCE. OBEDI + ENCE.",
    example: "The dog learned obedience through training.",
    difficulty: "medium",
    monthlySearches: "8,000+",
  },
  {
    word: "opportunity",
    misspellings: ["oportunity", "oppurtunity", "oppertunity", "opportuniy"],
    dialects: null,
    tip: "Two P's. OP + PORT + UNITY.",
    example: "This is a great opportunity for growth.",
    difficulty: "medium",
    monthlySearches: "15,000+",
  },
  {
    word: "optimistic",
    misspellings: ["optomistic", "optimistik", "optimestic", "optamistic"],
    dialects: null,
    tip: "OPTIM + ISTIC. Not OPTOM.",
    example: "She remained optimistic despite the setbacks.",
    difficulty: "medium",
    monthlySearches: "8,000+",
  },
  {
    word: "parallel",
    misspellings: ["paralell", "parrallel", "paralel", "parallell"],
    dialects: null,
    tip: "Three L's total: one in the middle, two at the end. PARA + LLEL.",
    example: "The two roads run parallel to each other.",
    difficulty: "hard",
    monthlySearches: "12,000+",
  },
  {
    word: "parliament",
    misspellings: ["parliment", "parlimant", "parliment", "parlement"],
    dialects: null,
    tip: "PARLIA + MENT. I before A.",
    example: "The new bill passed through parliament.",
    difficulty: "medium",
    monthlySearches: "10,000+",
  },
  {
    word: "peculiar",
    misspellings: ["peculier", "peuliar", "peculliar", "peculair"],
    dialects: null,
    tip: "PECULI + AR. Ends in AR, not ER.",
    example: "There was a peculiar smell in the room.",
    difficulty: "medium",
    monthlySearches: "8,000+",
  },
  {
    word: "permanent",
    misspellings: ["perminant", "permanant", "permenant", "permenent"],
    dialects: null,
    tip: "Ends in NENT, not NANT. PERMA + NENT.",
    example: "Is this a permanent position?",
    difficulty: "medium",
    monthlySearches: "10,000+",
  },
  {
    word: "phenomenon",
    misspellings: ["phenomemon", "phenominon", "phenomenom", "phenomonon"],
    dialects: null,
    tip: "PHENO + MENON. Ends in NON.",
    example: "Northern lights are a natural phenomenon.",
    difficulty: "hard",
    monthlySearches: "10,000+",
  },
  {
    word: "plagiarism",
    misspellings: ["plagerism", "plagarism", "plaigarism", "plagirism"],
    dialects: null,
    tip: "PLAGI + AR + ISM. Not PLAGER.",
    example: "Plagiarism is a serious academic offense.",
    difficulty: "hard",
    monthlySearches: "10,000+",
  },
  {
    word: "pneumonia",
    misspellings: ["pnemonia", "neumonia", "pneumona", "pnuemonia"],
    dialects: null,
    tip: "Silent P. PNEU + MONIA.",
    example: "He was hospitalized with pneumonia.",
    difficulty: "hard",
    monthlySearches: "15,000+",
  },
  {
    word: "potato",
    misspellings: ["potatoe", "potatos", "pottato", "patato"],
    dialects: null,
    tip: "No E at the end. Plural is POTATOES (with E).",
    example: "She baked a potato for dinner.",
    difficulty: "easy",
    monthlySearches: "10,000+",
  },
  {
    word: "precede",
    misspellings: ["preceed", "presede", "procede", "preceede"],
    dialects: null,
    tip: "PRE + CEDE. Not CEED. CEDE means to go.",
    example: "Thunder precedes lightning by seconds.",
    difficulty: "medium",
    monthlySearches: "8,000+",
  },
  {
    word: "prejudice",
    misspellings: ["predjudice", "prejudise", "predjuice", "prejudace"],
    dialects: null,
    tip: "PRE + JUDICE. Pre-judging someone.",
    example: "We must fight against prejudice.",
    difficulty: "medium",
    monthlySearches: "10,000+",
  },
  {
    word: "professor",
    misspellings: ["proffessor", "professer", "proffesser", "profeser"],
    dialects: null,
    tip: "One F, two S's. PRO + FESSOR.",
    example: "The professor gave an inspiring lecture.",
    difficulty: "medium",
    monthlySearches: "10,000+",
  },
  {
    word: "publicly",
    misspellings: ["publically", "publicaly", "publickly", "pubicly"],
    dialects: null,
    tip: "PUBLIC + LY. No AL in between.",
    example: "She publicly apologized for the mistake.",
    difficulty: "medium",
    monthlySearches: "8,000+",
  },
  {
    word: "recognise",
    misspellings: ["reconise", "recoginse", "recognice", "reconize"],
    dialects: { us: "recognize", uk: "recognise", au: "recognise", nz: "recognise" },
    tip: "RE + COGN + ISE/IZE. Think: re-cognition.",
    example: "I didn't recognise him with his new haircut.",
    difficulty: "medium",
    monthlySearches: "12,000+",
  },
  {
    word: "reference",
    misspellings: ["refrence", "referance", "refernce", "referrence"],
    dialects: null,
    tip: "REFER + ENCE. Don't drop the E.",
    example: "Can you provide a reference for the job?",
    difficulty: "easy",
    monthlySearches: "10,000+",
  },
  {
    word: "relevant",
    misspellings: ["relevent", "relavent", "relavant", "relevint"],
    dialects: null,
    tip: "Ends in ANT, not ENT. RELEV + ANT.",
    example: "Is this information relevant to the case?",
    difficulty: "medium",
    monthlySearches: "10,000+",
  },
  {
    word: "religious",
    misspellings: ["religous", "religios", "relgious", "religiuos"],
    dialects: null,
    tip: "RELIGI + OUS. I before O.",
    example: "They observed the religious holiday.",
    difficulty: "easy",
    monthlySearches: "8,000+",
  },
  {
    word: "remember",
    misspellings: ["remeber", "rember", "remmember", "remembar"],
    dialects: null,
    tip: "RE + MEM + BER. MEMBER is inside it.",
    example: "Do you remember where we parked?",
    difficulty: "easy",
    monthlySearches: "12,000+",
  },
  {
    word: "repetition",
    misspellings: ["repitition", "repetision", "repettion", "repetishon"],
    dialects: null,
    tip: "REPETI + TION. Think: REPEAT becomes REPETI.",
    example: "Repetition is the key to learning.",
    difficulty: "medium",
    monthlySearches: "8,000+",
  },
  {
    word: "resistance",
    misspellings: ["resistence", "resistanse", "resitance", "resistince"],
    dialects: null,
    tip: "Ends in ANCE, not ENCE. RESIST + ANCE.",
    example: "There was strong resistance to the new policy.",
    difficulty: "medium",
    monthlySearches: "8,000+",
  },
  {
    word: "sacrifice",
    misspellings: ["sacrifise", "sacrafice", "sacrifce", "sacrifiec"],
    dialects: null,
    tip: "SACRI + FICE. Think: sacred office.",
    example: "Parents often make sacrifices for their children.",
    difficulty: "medium",
    monthlySearches: "10,000+",
  },
  {
    word: "sandwich",
    misspellings: ["sandwitch", "sanwich", "sandwhich", "sandwhitch"],
    dialects: null,
    tip: "SAND + WICH. Named after the Earl of Sandwich.",
    example: "I had a turkey sandwich for lunch.",
    difficulty: "easy",
    monthlySearches: "10,000+",
  },
  {
    word: "scissors",
    misspellings: ["sissors", "scisors", "scissers", "scizzors"],
    dialects: null,
    tip: "SC + ISS + ORS. Silent C at the start.",
    example: "Pass me the scissors, please.",
    difficulty: "medium",
    monthlySearches: "10,000+",
  },
  {
    word: "sergeant",
    misspellings: ["sargent", "sargeant", "sergant", "seargent"],
    dialects: null,
    tip: "SER + GEANT. The G before E is unusual.",
    example: "The sergeant led the training exercise.",
    difficulty: "hard",
    monthlySearches: "10,000+",
  },
  {
    word: "silhouette",
    misspellings: ["silouette", "silhoette", "silouhette", "silhouete"],
    dialects: null,
    tip: "Named after Etienne de Silhouette. SILHOU + ETTE.",
    example: "She could see his silhouette in the doorway.",
    difficulty: "hard",
    monthlySearches: "10,000+",
  },
  {
    word: "similar",
    misspellings: ["similer", "similiar", "similiar", "simmiler"],
    dialects: null,
    tip: "SIMIL + AR. Ends in AR, not ER.",
    example: "The two paintings look very similar.",
    difficulty: "easy",
    monthlySearches: "12,000+",
  },
  {
    word: "sincerely",
    misspellings: ["sincerly", "sinceerly", "sincerley", "sincearly"],
    dialects: null,
    tip: "SINCERE + LY. Keep the E.",
    example: "Yours sincerely, John Smith.",
    difficulty: "easy",
    monthlySearches: "10,000+",
  },
  {
    word: "speech",
    misspellings: ["speach", "speetch", "speeh", "spech"],
    dialects: null,
    tip: "Double E. SP + EECH.",
    example: "She delivered an inspiring speech.",
    difficulty: "easy",
    monthlySearches: "10,000+",
  },
  {
    word: "strength",
    misspellings: ["strenght", "strenth", "stength", "strengh"],
    dialects: null,
    tip: "STRENG + TH. The G comes before TH.",
    example: "He admired her inner strength.",
    difficulty: "easy",
    monthlySearches: "10,000+",
  },
  {
    word: "successful",
    misspellings: ["succesful", "successfull", "succesfull", "succcesfull"],
    dialects: null,
    tip: "Two C's, two S's, one L. SUCCESS + FUL.",
    example: "The event was extremely successful.",
    difficulty: "medium",
    monthlySearches: "20,000+",
  },
  {
    word: "surprise",
    misspellings: ["surprize", "suprise", "surprice", "surpise"],
    dialects: null,
    tip: "Two R's. SUR + PRISE. Not prize.",
    example: "The party was a complete surprise.",
    difficulty: "easy",
    monthlySearches: "15,000+",
  },
  {
    word: "temperature",
    misspellings: ["temperture", "tempreture", "tempercher", "temparature"],
    dialects: null,
    tip: "TEMPER + A + TURE. Don't skip the A.",
    example: "The temperature dropped below freezing.",
    difficulty: "medium",
    monthlySearches: "15,000+",
  },
  {
    word: "thorough",
    misspellings: ["thorogh", "thourgh", "thorugh", "thurrough"],
    dialects: null,
    tip: "THOROUGH, not through. O + U + G + H at the end.",
    example: "She did a thorough investigation.",
    difficulty: "medium",
    monthlySearches: "10,000+",
  },
  {
    word: "threshold",
    misspellings: ["threshhold", "treshold", "thresold", "threshhold"],
    dialects: null,
    tip: "One H in the middle. THRESH + OLD.",
    example: "We are on the threshold of a new era.",
    difficulty: "medium",
    monthlySearches: "8,000+",
  },
  {
    word: "tongue",
    misspellings: ["tounge", "tunge", "tongeu", "tonge"],
    dialects: null,
    tip: "TONG + UE. The UE is at the end.",
    example: "Bite your tongue before you say something rude.",
    difficulty: "easy",
    monthlySearches: "12,000+",
  },
  {
    word: "truly",
    misspellings: ["truely", "truley", "trully", "trooly"],
    dialects: null,
    tip: "TRUE drops the E. TRU + LY.",
    example: "I am truly grateful for your help.",
    difficulty: "easy",
    monthlySearches: "12,000+",
  },
  {
    word: "tyranny",
    misspellings: ["tyrany", "tyrrany", "tyranny", "tirrany"],
    dialects: null,
    tip: "One R, two N's. TY + RANNY.",
    example: "The people revolted against tyranny.",
    difficulty: "medium",
    monthlySearches: "8,000+",
  },
  {
    word: "unnecessary",
    misspellings: ["unneccesary", "unecessary", "unnecesary", "unnecessery"],
    dialects: null,
    tip: "UN + NECESSARY. One C, two S's.",
    example: "Avoid unnecessary expenses.",
    difficulty: "hard",
    monthlySearches: "15,000+",
  },
  {
    word: "until",
    misspellings: ["untill", "untl", "untile", "untell"],
    dialects: null,
    tip: "One L at the end. UN + TIL.",
    example: "Wait until the light turns green.",
    difficulty: "easy",
    monthlySearches: "10,000+",
  },
  {
    word: "vehicle",
    misspellings: ["vehical", "vehicel", "vehcle", "vehicale"],
    dialects: null,
    tip: "VE + HICLE. Ends in CLE, not CAL.",
    example: "The vehicle was parked in the driveway.",
    difficulty: "medium",
    monthlySearches: "12,000+",
  },
  {
    word: "visible",
    misspellings: ["visable", "visibel", "visble", "visabel"],
    dialects: null,
    tip: "Ends in IBLE, not ABLE. VIS + IBLE.",
    example: "The mountain was visible from the highway.",
    difficulty: "easy",
    monthlySearches: "8,000+",
  },
  {
    word: "weather",
    misspellings: ["wether", "wheather", "waether", "weahter"],
    dialects: null,
    tip: "WEA + THER. Don't confuse with whether (choice) or wether (sheep).",
    example: "The weather forecast calls for rain.",
    difficulty: "easy",
    monthlySearches: "15,000+",
  },
  {
    word: "Wednesday",
    misspellings: ["Wensday", "Wendsday", "Wendesday", "Wedensday"],
    dialects: null,
    tip: "WED + NES + DAY. Named after Woden (Norse god). The D is silent.",
    example: "The meeting is scheduled for Wednesday.",
    difficulty: "easy",
    monthlySearches: "25,000+",
  },
  {
    word: "writing",
    misspellings: ["writting", "writeing", "writting", "riting"],
    dialects: null,
    tip: "One T. WRITE drops the E, adds ING.",
    example: "She is passionate about creative writing.",
    difficulty: "easy",
    monthlySearches: "10,000+",
  },
  // Dialect-heavy words - US/UK/AU/NZ spelling differences
  {
    word: "colour",
    misspellings: ["colur", "coulor", "coler", "coular"],
    dialects: { us: "color", uk: "colour", au: "colour", nz: "colour" },
    tip: "US drops the U: color. UK/AU/NZ keep it: colour.",
    example: "What colour is the sky?",
    difficulty: "easy",
    monthlySearches: "50,000+",
  },
  {
    word: "favourite",
    misspellings: ["favrite", "favorit", "faverite", "favurite"],
    dialects: { us: "favorite", uk: "favourite", au: "favourite", nz: "favourite" },
    tip: "US: favorite (no U). UK/AU/NZ: favourite (with U).",
    example: "Pizza is my favourite food.",
    difficulty: "easy",
    monthlySearches: "40,000+",
  },
  {
    word: "honour",
    misspellings: ["honer", "honur", "honnor", "honner"],
    dialects: { us: "honor", uk: "honour", au: "honour", nz: "honour" },
    tip: "US: honor. UK/AU/NZ: honour. Both are correct in their regions.",
    example: "It is an honour to meet you.",
    difficulty: "easy",
    monthlySearches: "25,000+",
  },
  {
    word: "neighbour",
    misspellings: ["neigbour", "nieghbor", "neighbur", "neigbor"],
    dialects: { us: "neighbor", uk: "neighbour", au: "neighbour", nz: "neighbour" },
    tip: "US: neighbor. UK/AU/NZ: neighbour. EI not IE, then GHBOUR.",
    example: "Our neighbour has a lovely garden.",
    difficulty: "medium",
    monthlySearches: "20,000+",
  },
  {
    word: "organise",
    misspellings: ["orginise", "organice", "oragnise", "orgainse"],
    dialects: { us: "organize", uk: "organise", au: "organise", nz: "organise" },
    tip: "US uses Z: organize. UK/AU/NZ use S: organise.",
    example: "Let me organise the files for you.",
    difficulty: "easy",
    monthlySearches: "20,000+",
  },
  {
    word: "travelling",
    misspellings: ["travaling", "travilling", "travellin", "travelig"],
    dialects: { us: "traveling", uk: "travelling", au: "travelling", nz: "travelling" },
    tip: "US: one L (traveling). UK/AU/NZ: two L's (travelling).",
    example: "She enjoys travelling to new countries.",
    difficulty: "easy",
    monthlySearches: "25,000+",
  },
  {
    word: "behaviour",
    misspellings: ["behavour", "behavoir", "behaveur", "behavor"],
    dialects: { us: "behavior", uk: "behaviour", au: "behaviour", nz: "behaviour" },
    tip: "US: behavior. UK/AU/NZ: behaviour (with U).",
    example: "His behaviour in class has improved.",
    difficulty: "medium",
    monthlySearches: "20,000+",
  },
  {
    word: "catalogue",
    misspellings: ["catelog", "cataloge", "catalague", "catalouge"],
    dialects: { us: "catalog", uk: "catalogue", au: "catalogue", nz: "catalogue" },
    tip: "US often uses catalog. UK/AU/NZ use catalogue (with UE).",
    example: "Browse our product catalogue online.",
    difficulty: "medium",
    monthlySearches: "15,000+",
  },
  {
    word: "defence",
    misspellings: ["defance", "defanse", "defince", "deffence"],
    dialects: { us: "defense", uk: "defence", au: "defence", nz: "defence" },
    tip: "US: defense (with S). UK/AU/NZ: defence (with C).",
    example: "The team's defence was outstanding.",
    difficulty: "easy",
    monthlySearches: "20,000+",
  },
  {
    word: "licence",
    misspellings: ["lisence", "licanse", "lisense", "licience"],
    dialects: { us: "license", uk: "licence", au: "licence", nz: "licence" },
    tip: "US: license for both noun and verb. UK: licence (noun) and license (verb).",
    example: "You need a licence to drive.",
    difficulty: "medium",
    monthlySearches: "25,000+",
  },
  {
    word: "programme",
    misspellings: ["programm", "programee", "programe", "programm"],
    dialects: { us: "program", uk: "programme", au: "programme", nz: "programme" },
    tip: "US: program. UK/AU/NZ: programme (except for computer programs).",
    example: "The evening programme includes a concert.",
    difficulty: "medium",
    monthlySearches: "15,000+",
  },
  {
    word: "realise",
    misspellings: ["reelize", "realice", "reilise", "realease"],
    dialects: { us: "realize", uk: "realise", au: "realise", nz: "realise" },
    tip: "US: realize (with Z). UK/AU/NZ: realise (with S).",
    example: "I didn't realise how late it was.",
    difficulty: "easy",
    monthlySearches: "15,000+",
  },
  {
    word: "apologise",
    misspellings: ["apoligise", "appologise", "apoligize", "appologize"],
    dialects: { us: "apologize", uk: "apologise", au: "apologise", nz: "apologise" },
    tip: "US: apologize (Z). UK/AU/NZ: apologise (S).",
    example: "I must apologise for the delay.",
    difficulty: "medium",
    monthlySearches: "15,000+",
  },
  {
    word: "analyse",
    misspellings: ["analize", "analise", "annalyse", "anaylse"],
    dialects: { us: "analyze", uk: "analyse", au: "analyse", nz: "analyse" },
    tip: "US: analyze (Z). UK/AU/NZ: analyse (S).",
    example: "We need to analyse the data carefully.",
    difficulty: "medium",
    monthlySearches: "15,000+",
  },
  {
    word: "centre",
    misspellings: ["senter", "sentre", "centir", "centar"],
    dialects: { us: "center", uk: "centre", au: "centre", nz: "centre" },
    tip: "US: center (ER). UK/AU/NZ: centre (RE).",
    example: "The shopping centre is in the middle of town.",
    difficulty: "easy",
    monthlySearches: "20,000+",
  },
  {
    word: "grey",
    misspellings: ["grei", "grae", "greyy", "gre"],
    dialects: { us: "gray", uk: "grey", au: "grey", nz: "grey" },
    tip: "US: grAy (A for America). UK/AU/NZ: grEy (E for England).",
    example: "The sky was a dull shade of grey.",
    difficulty: "easy",
    monthlySearches: "20,000+",
  },
  {
    word: "practise",
    misspellings: ["practis", "practtice", "practace", "practiss"],
    dialects: { us: "practice", uk: "practise", au: "practise", nz: "practise" },
    tip: "US: practice for both. UK: practise (verb) vs practice (noun).",
    example: "You need to practise every day.",
    difficulty: "medium",
    monthlySearches: "15,000+",
  },
  {
    word: "cheque",
    misspellings: ["chek", "checque", "cheqe", "chueqe"],
    dialects: { us: "check", uk: "cheque", au: "cheque", nz: "cheque" },
    tip: "US: check. UK/AU/NZ: cheque (for bank payments).",
    example: "She wrote a cheque for the deposit.",
    difficulty: "medium",
    monthlySearches: "12,000+",
  },
  {
    word: "sceptic",
    misspellings: ["skeptik", "sceptik", "sceptic", "sceptick"],
    dialects: { us: "skeptic", uk: "sceptic", au: "sceptic", nz: "sceptic" },
    tip: "US: skeptic (SK). UK/AU/NZ: sceptic (SC).",
    example: "He remains a sceptic about climate predictions.",
    difficulty: "medium",
    monthlySearches: "10,000+",
  },
  {
    word: "labour",
    misspellings: ["laber", "labur", "laybour", "labore"],
    dialects: { us: "labor", uk: "labour", au: "labour", nz: "labour" },
    tip: "US: labor. UK/AU/NZ: labour (with U).",
    example: "The project required months of hard labour.",
    difficulty: "easy",
    monthlySearches: "15,000+",
  },
]

// Helper to get word by slug
export function getWordBySlug(slug: string): SpellingWord | undefined {
  return SPELLING_WORDS.find(
    (w) => w.word.toLowerCase().replace(/[' ]/g, "-") === slug.toLowerCase()
  )
}

// Get all slugs for static generation
export function getAllSlugs(): string[] {
  return SPELLING_WORDS.map((w) => w.word.toLowerCase().replace(/[' ]/g, "-"))
}
