export type SpellingWord = {
  word: string
  misspellings: string[]
  dialects: { us: string; uk: string; au: string; nz: string } | null
  tip: string
  example: string
  difficulty: "easy" | "medium" | "hard"
  monthlySearches: string
}

export const SPELLING_WORDS: SpellingWord[] = [
  {
    word: "accommodate",
    misspellings: ["accomodate", "acommodate", "acomodate", "accommadate"],
    dialects: null,
    tip: "Two c's and two m's. Think: it's large enough to accommodate two of each.",
    example: "The hotel can accommodate up to 300 guests.",
    difficulty: "hard",
    monthlySearches: "100,000+",
  },
  {
    word: "achieve",
    misspellings: ["acheive", "acheve", "acheeve"],
    dialects: null,
    tip: "I before E, except after C. Achieve follows the rule.",
    example: "She worked hard to achieve her goals.",
    difficulty: "easy",
    monthlySearches: "30,000+",
  },
  {
    word: "acquire",
    misspellings: ["aquire", "adquire", "accquire", "aqcuire"],
    dialects: null,
    tip: "AC then QUIRE. Think: I need to ACquire new skills.",
    example: "The company plans to acquire a smaller firm.",
    difficulty: "medium",
    monthlySearches: "25,000+",
  },
  {
    word: "alphabet",
    misspellings: ["alphubet", "alfabet", "alphbet", "alphabit"],
    dialects: null,
    tip: "Alpha + bet. Two Greek letters combined.",
    example: "Children learn the alphabet in kindergarten.",
    difficulty: "easy",
    monthlySearches: "15,000+",
  },
  {
    word: "apparently",
    misspellings: ["apparantly", "aparently", "apparentley", "aparantly"],
    dialects: null,
    tip: "Parent is hiding inside: apPARENTly.",
    example: "Apparently, the meeting has been moved to Friday.",
    difficulty: "medium",
    monthlySearches: "40,000+",
  },
  {
    word: "beautiful",
    misspellings: ["beautifull", "beutiful", "beautful", "beatiful"],
    dialects: null,
    tip: "Big Elephants Are Ugly. The first letters spell BEAU.",
    example: "The sunset was absolutely beautiful.",
    difficulty: "easy",
    monthlySearches: "50,000+",
  },
  {
    word: "believe",
    misspellings: ["beleive", "belive", "beleave", "beleve"],
    dialects: null,
    tip: "Never beLIEve a LIE.",
    example: "I believe we can finish on time.",
    difficulty: "easy",
    monthlySearches: "20,000+",
  },
  {
    word: "bureaucracy",
    misspellings: ["beaurocracy", "burocracy", "beurocracy", "bureacracy"],
    dialects: null,
    tip: "BUREAU + CRACY. A bureau that rules.",
    example: "The bureaucracy made the process slow.",
    difficulty: "hard",
    monthlySearches: "25,000+",
  },
  {
    word: "calendar",
    misspellings: ["calender", "calander", "calandar", "callendar"],
    dialects: null,
    tip: "Ends in DAR, not DER. Think: Mark the DAR on the calendar.",
    example: "Please check the calendar for available dates.",
    difficulty: "easy",
    monthlySearches: "257,000",
  },
  {
    word: "Caribbean",
    misspellings: ["Carribean", "Caribean", "Caribbian", "Carribbean"],
    dialects: null,
    tip: "One R, two B's. The opposite of what you'd expect.",
    example: "They sailed across the Caribbean Sea.",
    difficulty: "hard",
    monthlySearches: "30,000+",
  },
  {
    word: "cemetery",
    misspellings: ["cemetary", "cematery", "cemetry", "cemetary"],
    dialects: null,
    tip: "Three E's, no A's. Think: E-E-E, screaming in a cemetery.",
    example: "The old cemetery dates back to the 1800s.",
    difficulty: "medium",
    monthlySearches: "20,000+",
  },
  {
    word: "colleague",
    misspellings: ["collegue", "colague", "coleague", "colleage"],
    dialects: null,
    tip: "Ends in LEAGUE, like a team of colleagues.",
    example: "My colleague helped me with the project.",
    difficulty: "medium",
    monthlySearches: "25,000+",
  },
  {
    word: "conscience",
    misspellings: ["concience", "consience", "concsience", "conshence"],
    dialects: null,
    tip: "CON + SCIENCE. Your inner science of right and wrong.",
    example: "His conscience told him to return the wallet.",
    difficulty: "hard",
    monthlySearches: "60,000+",
  },
  {
    word: "conscientious",
    misspellings: ["concientious", "consciencious", "conscienscious"],
    dialects: null,
    tip: "CONSCIENCE + TIOUS. Being guided by your conscience.",
    example: "She is a conscientious worker who checks every detail.",
    difficulty: "hard",
    monthlySearches: "25,000+",
  },
  {
    word: "congratulations",
    misspellings: ["congradulations", "congragulations", "congraulations"],
    dialects: null,
    tip: "No D. It comes from GRATULATE, not GRADUATE.",
    example: "Congratulations on your promotion!",
    difficulty: "medium",
    monthlySearches: "40,000+",
  },
  {
    word: "definitely",
    misspellings: ["definately", "definatly", "defiantly", "definetly", "definatley"],
    dialects: null,
    tip: "FINITE is in the middle: deFINITEly. No A anywhere.",
    example: "I will definitely be there by noon.",
    difficulty: "medium",
    monthlySearches: "150,000+",
  },
  {
    word: "diarrhea",
    misspellings: ["diarhea", "diarrhoea", "diarreah", "diarea"],
    dialects: { us: "diarrhea", uk: "diarrhoea", au: "diarrhoea", nz: "diarrhoea" },
    tip: "Two R's, then H. Dash In A Rush, Run Hard, Else Accident.",
    example: "The patient was treated for diarrhea.",
    difficulty: "hard",
    monthlySearches: "35,000+",
  },
  {
    word: "dilemma",
    misspellings: ["dilema", "dilemna", "dillema", "dillemma"],
    dialects: null,
    tip: "Two M's, not N. Think: Emma has a dilemma.",
    example: "He faced a dilemma between two job offers.",
    difficulty: "medium",
    monthlySearches: "15,000+",
  },
  {
    word: "disappoint",
    misspellings: ["dissapoint", "disapoint", "disappoint", "dissappoint"],
    dialects: null,
    tip: "One S, two P's. DIS + APPOINT.",
    example: "I hope the results don't disappoint you.",
    difficulty: "medium",
    monthlySearches: "20,000+",
  },
  {
    word: "embarrass",
    misspellings: ["embarass", "embarras", "embaress", "embaras"],
    dialects: null,
    tip: "Two R's and two S's. It's Really Really Stressful and Shameful.",
    example: "Please don't embarrass me in public.",
    difficulty: "medium",
    monthlySearches: "60,000+",
  },
  {
    word: "environment",
    misspellings: ["enviroment", "envirnoment", "enviornment", "enviorment"],
    dialects: null,
    tip: "IRON is hiding in the middle: envIRONment.",
    example: "We must protect the environment for future generations.",
    difficulty: "medium",
    monthlySearches: "30,000+",
  },
  {
    word: "exaggerate",
    misspellings: ["exagerate", "exadgerate", "exaggerrate", "exaggurate"],
    dialects: null,
    tip: "Two G's. You're exaGGerating with extra G's.",
    example: "Don't exaggerate the problem.",
    difficulty: "medium",
    monthlySearches: "20,000+",
  },
  {
    word: "existence",
    misspellings: ["existance", "existense", "existince"],
    dialects: null,
    tip: "Ends in ENCE, not ANCE. Think: EXIST + ENCE.",
    example: "No one questioned the existence of the document.",
    difficulty: "medium",
    monthlySearches: "15,000+",
  },
  {
    word: "foreign",
    misspellings: ["foriegn", "forein", "foregin", "foren"],
    dialects: null,
    tip: "E before I. It breaks the I before E rule. FOR + EIGN.",
    example: "She speaks three foreign languages.",
    difficulty: "medium",
    monthlySearches: "20,000+",
  },
  {
    word: "gauge",
    misspellings: ["guage", "gage", "gaige", "gauje"],
    dialects: null,
    tip: "G-A-U, not G-U-A. Think: A U-turn after the A.",
    example: "Check the fuel gauge before driving.",
    difficulty: "hard",
    monthlySearches: "30,000+",
  },
  {
    word: "government",
    misspellings: ["goverment", "govenment", "governmant", "govermnent"],
    dialects: null,
    tip: "GOVERN + MENT. Don't drop the N.",
    example: "The government announced new policies.",
    difficulty: "easy",
    monthlySearches: "25,000+",
  },
  {
    word: "guarantee",
    misspellings: ["gaurantee", "guarentee", "garantee", "guaruntee"],
    dialects: null,
    tip: "GUA at the start, not GAU. Then RANTEE.",
    example: "We guarantee delivery within 24 hours.",
    difficulty: "hard",
    monthlySearches: "60,000+",
  },
  {
    word: "harass",
    misspellings: ["harrass", "harras", "haras", "herrass"],
    dialects: null,
    tip: "One R, two S's. Think: one Rude person causeS Stress.",
    example: "It is illegal to harass someone at work.",
    difficulty: "medium",
    monthlySearches: "30,000+",
  },
  {
    word: "hors d'oeuvre",
    misspellings: ["horderves", "ordeurves", "orderves", "hors doeuvres"],
    dialects: null,
    tip: "It's French. HORS (outside) + D'OEUVRE (the work). Appetizers served outside the main meal.",
    example: "They served hors d'oeuvres before dinner.",
    difficulty: "hard",
    monthlySearches: "20,000+",
  },
  {
    word: "independent",
    misspellings: ["independant", "independend", "indipendent", "indapendent"],
    dialects: null,
    tip: "Ends in DENT, not DANT. A DENT in dependence.",
    example: "She became financially independent at 25.",
    difficulty: "medium",
    monthlySearches: "50,000+",
  },
  {
    word: "jewelry",
    misspellings: ["jewellry", "jewlery", "jewelery", "jewlry"],
    dialects: { us: "jewelry", uk: "jewellery", au: "jewellery", nz: "jewellery" },
    tip: "US: JEWEL + RY. UK/AU/NZ: JEWEL + LERY.",
    example: "She wore her finest jewelry to the gala.",
    difficulty: "medium",
    monthlySearches: "25,000+",
  },
  {
    word: "knowledge",
    misspellings: ["knowlege", "knoledge", "knowlegde", "nowledge"],
    dialects: null,
    tip: "KNOW + LEDGE. Standing on the ledge of what you know.",
    example: "Knowledge is power.",
    difficulty: "easy",
    monthlySearches: "15,000+",
  },
  {
    word: "liaison",
    misspellings: ["liason", "liasion", "liaision", "leason"],
    dialects: null,
    tip: "Two I's: L-I-A-I-S-O-N. Think: I Always Irritate Spelling Obsessed Nerds.",
    example: "She serves as the liaison between the two departments.",
    difficulty: "hard",
    monthlySearches: "30,000+",
  },
  {
    word: "maintenance",
    misspellings: ["maintainance", "maintanence", "maintnance", "maintainence"],
    dialects: null,
    tip: "MAIN + TEN + ANCE. Not maintain + ance.",
    example: "Regular maintenance keeps the car running smoothly.",
    difficulty: "hard",
    monthlySearches: "60,000+",
  },
  {
    word: "millennium",
    misspellings: ["millenium", "milennium", "milleneum", "milenium"],
    dialects: null,
    tip: "Two L's and two N's. MILL + ENNIUM.",
    example: "The new millennium began in the year 2000.",
    difficulty: "hard",
    monthlySearches: "20,000+",
  },
  {
    word: "misspell",
    misspellings: ["mispell", "misspel", "mispel", "misspell"],
    dialects: null,
    tip: "MIS + SPELL. You need both S's. Ironic, isn't it?",
    example: "Don't misspell the client's name on the contract.",
    difficulty: "easy",
    monthlySearches: "257,000",
  },
  {
    word: "necessary",
    misspellings: ["neccessary", "necessery", "neccesary", "nesessary"],
    dialects: null,
    tip: "One C, two S's. A shirt has one Collar and two Sleeves.",
    example: "It is necessary to wear a helmet while cycling.",
    difficulty: "medium",
    monthlySearches: "60,000+",
  },
  {
    word: "occurrence",
    misspellings: ["occurence", "occurance", "occurrance", "ocurrence"],
    dialects: null,
    tip: "Two C's, two R's, then ENCE. Double trouble.",
    example: "This is an unusual occurrence.",
    difficulty: "hard",
    monthlySearches: "100,000+",
  },
  {
    word: "perseverance",
    misspellings: ["perserverance", "perseverence", "perseveranse", "perserverence"],
    dialects: null,
    tip: "PERSEVERE + ANCE. Sever is in the middle.",
    example: "Her perseverance paid off in the end.",
    difficulty: "hard",
    monthlySearches: "25,000+",
  },
  {
    word: "pharmaceutical",
    misspellings: ["farmaceutical", "pharmaseutical", "pharmeceutical", "pharmceutical"],
    dialects: null,
    tip: "PH not F. PHARMA + CEUTICAL.",
    example: "The pharmaceutical industry develops life-saving drugs.",
    difficulty: "hard",
    monthlySearches: "15,000+",
  },
  {
    word: "possession",
    misspellings: ["posession", "possesion", "posesion", "possestion"],
    dialects: null,
    tip: "Two S's, then two S's again. Double double S's.",
    example: "The stolen goods were found in his possession.",
    difficulty: "medium",
    monthlySearches: "15,000+",
  },
  {
    word: "privilege",
    misspellings: ["privelege", "priviledge", "privlege", "privilige"],
    dialects: null,
    tip: "No D. PRIVI + LEGE. It's a legal term (lege = law).",
    example: "Education is a privilege, not a right.",
    difficulty: "hard",
    monthlySearches: "40,000+",
  },
  {
    word: "pronunciation",
    misspellings: ["pronounciation", "pronuncation", "pronouncation", "prononsiation"],
    dialects: null,
    tip: "No OUNCE. It's PRONUNCI + ATION, not pronounce + ation.",
    example: "Her pronunciation of French words is excellent.",
    difficulty: "hard",
    monthlySearches: "30,000+",
  },
  {
    word: "quarantine",
    misspellings: ["quarentine", "quarintine", "quaranteen", "quarentene"],
    dialects: null,
    tip: "QUARAN + TINE. From the Italian quaranta (forty days).",
    example: "Travelers were placed in quarantine for two weeks.",
    difficulty: "medium",
    monthlySearches: "40,000+",
  },
  {
    word: "questionnaire",
    misspellings: ["questionaire", "questionairre", "questionnare", "questionair"],
    dialects: null,
    tip: "Two N's and ends in AIRE. QUESTION + NAIRE.",
    example: "Please fill out this questionnaire.",
    difficulty: "hard",
    monthlySearches: "30,000+",
  },
  {
    word: "receive",
    misspellings: ["recieve", "receve", "receave", "recive"],
    dialects: null,
    tip: "I before E except after C. reCEIve.",
    example: "You will receive a confirmation email shortly.",
    difficulty: "easy",
    monthlySearches: "80,000+",
  },
  {
    word: "recommend",
    misspellings: ["recomend", "reccommend", "reccomend", "recommand"],
    dialects: null,
    tip: "One C, two M's. Think: I recommend more M&Ms.",
    example: "I highly recommend this restaurant.",
    difficulty: "medium",
    monthlySearches: "30,000+",
  },
  {
    word: "restaurant",
    misspellings: ["restaraunt", "resturant", "restraunt", "resteraunt", "restrant"],
    dialects: null,
    tip: "REST + AU + RANT. You REST while someone rants about the AUbergine.",
    example: "The new restaurant downtown has great reviews.",
    difficulty: "medium",
    monthlySearches: "100,000+",
  },
  {
    word: "rhythm",
    misspellings: ["rythm", "rythym", "rhythym", "rithm"],
    dialects: null,
    tip: "Rhythm Has Your Two Hips Moving.",
    example: "The drummer kept a steady rhythm.",
    difficulty: "hard",
    monthlySearches: "50,000+",
  },
  {
    word: "schedule",
    misspellings: ["shedule", "scedule", "schedual", "schadule"],
    dialects: null,
    tip: "SCH at the start, like SCHOOL. SCHED + ULE.",
    example: "Check the schedule for meeting times.",
    difficulty: "medium",
    monthlySearches: "20,000+",
  },
  {
    word: "separate",
    misspellings: ["seperate", "seprate", "separete", "separet"],
    dialects: null,
    tip: "There's A RAT in sepARAte.",
    example: "Please separate the whites from the colors.",
    difficulty: "medium",
    monthlySearches: "100,000+",
  },
  {
    word: "supersede",
    misspellings: ["supercede", "superceed", "superseed", "superceed"],
    dialects: null,
    tip: "Ends in SEDE, not CEDE. It's the only English word that does.",
    example: "The new policy will supersede the old one.",
    difficulty: "hard",
    monthlySearches: "15,000+",
  },
  {
    word: "tomorrow",
    misspellings: ["tommorrow", "tommorow", "tomorow", "tommorrow"],
    dialects: null,
    tip: "One M, two R's. TOM + OR + ROW.",
    example: "We'll finish the project tomorrow.",
    difficulty: "easy",
    monthlySearches: "30,000+",
  },
  {
    word: "vacuum",
    misspellings: ["vaccum", "vacume", "vaccuum", "vacum"],
    dialects: null,
    tip: "One C, two U's. The vacuum sucks up U's.",
    example: "Please vacuum the living room before guests arrive.",
    difficulty: "medium",
    monthlySearches: "25,000+",
  },
  {
    word: "weird",
    misspellings: ["wierd", "weerd", "wird", "werid"],
    dialects: null,
    tip: "WE are WEIRD. E before I. It breaks the rule, because it's weird.",
    example: "That was a weird coincidence.",
    difficulty: "easy",
    monthlySearches: "15,000+",
  },
]

// Helper to get word by slug
export function getWordBySlug(slug: string): SpellingWord | undefined {
  return SPELLING_WORDS.find(
    (w) => w.word.toLowerCase().replace(/[' ]/g, "-") === slug.toLowerCase()
  )
}

// Get all slugs for static generation
export function getAllSlugs(): string[] {
  return SPELLING_WORDS.map((w) => w.word.toLowerCase().replace(/[' ]/g, "-"))
}
